### ISSUE TITLE
Upcoming alarm tab is blank

### ISSUE THREAD

**Issue by hirenchalodiya1** [devlup-labs/meet-scheduler#34]
### Issue
- `upcoming` is blank even after adding 5 courses
![image](https://user-images.githubusercontent.com/32496777/93845028-fc969680-fcbc-11ea-929b-0821ac42e0c4.png)

### Possible explanation
- It's taking too much time to render list item(In my case it is 40 items)

**Comment by DarshitJain04** [comment]
@hirenchalodiya1  @manav1403 made changes to the API call. Should work fine now.

**Comment by manav1403** [comment]
addressed in #33

**Comment by hirenchalodiya1** [comment]
`https://github.com/devlup-labs/meet-scheduler/blob/6bf9318766faaeac29f4ced9207c2b1158f7ce63/src/pages/Popup/scripts/fetchSheet.js`
Solve something like this

**Comment by hirenchalodiya1** [comment]
You may face `failed to execute 'json' on 'response' body stream already read` issue

**Comment by hirenchalodiya1** [comment]
@DarshitJain04 @manav1403 look into this
