### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by anshulahuja98** [devlup-labs/meet-scheduler#41]
Make the colour change in the save button more prominent when it is clickable or not.
![image](https://user-images.githubusercontent.com/36476228/93968594-96c31100-fd87-11ea-87ef-b6a52368c37e.png)

Make it more clear that this clock button is clickable. Maybe add a tick in default?
![image](https://user-images.githubusercontent.com/36476228/93968740-eefa1300-fd87-11ea-86c5-94860296b096.png)

**Comment by neeraj-2** [comment]
I would like to work on it

**Comment by anshulahuja98** [comment]
Sure @neeraj-2 feel free to drop a PR.

**Comment by neeraj-2** [comment]
> Sure @neeraj-2 feel free to drop a PR.

👍

**Comment by neeraj-2** [comment]
Can you suggest some prominent color for save button. Actually ,i don't have enough idea of UI .Like ,i tried with success color button. Suggest some?
![image](https://user-images.githubusercontent.com/56186425/94025784-85552580-fdd6-11ea-88a1-081cd1460f71.png)

**Comment by anshulahuja98** [comment]
You can either pickup the shade of blue in the extension theme in general.
Or "success" doesn't look bad either

@DarshitJain04 you can give him suggestions

**Comment by DarshitJain04** [comment]
> You can either pickup the shade of blue in the extension theme in general.
> Or "success" doesn't look bad either
> 
> @DarshitJain04 you can give him suggestions

Yeah sure!
@neeraj-2 currently we're using Indigo colour. So a lighter shade of Indigo can be given to the disabled button and when it's not disabled, change it to the original colour.
Works? @anshulahuja98

**Comment by anshulahuja98** [comment]
For disabled maybe go for light grey? Like right now.

**Comment by DarshitJain04** [comment]
` #E8EAF6 ` can be used. Very light with a shade of Indigo

**Comment by hirenchalodiya1** [comment]
There are two toggles in the screen name as `auto join`, and maybe the second text can be changed as `auto join in class`.

**Comment by neeraj-2** [comment]
I have made  a PR #48 ,have a review and merge if it is Okay.
