### ISSUE TITLE
Add dedicated icon 

### ISSUE THREAD

**Issue by anshulahuja98** [devlup-labs/meet-scheduler#51]
Create a simple icon for the extension

**Comment by nidhishs** [comment]
Hey, I have some experience with graphic designing and illustrator. I can help you guys design a custom icon.

**Comment by anshulahuja98** [comment]
Sure @nidhishs  that would be great!
A minimalist icon which can perhaps be something related to video call and a timer of sorts.
Or I'll open it up to your thinking.
Hit us up in the comments here with your proposed designs. You can later send a PR of the same.

**Comment by nidhishs** [comment]
> Sure @nidhishs that would be great!
> A minimalist icon which can perhaps be something related to video call and a timer of sorts.
> Or I'll open it up to your thinking.
> Hit us up in the comments here with your proposed designs. You can later send a PR of the same.

Sure, I'll send some designs by Sunday.

**Comment by nidhishs** [comment]
Do you guys have requirements, such as any colour schemes? Do you want me to base my icon on the google meet icon?

Also, if you don't mind and approve the designs, can I send the PR in October so it also get's counted for Hacktoberfest?

**Comment by anshulahuja98** [comment]
We do not have any strict requirements, just try to keep it minimalist.

Don't use the google meet icon directly, it might lead to some copyright conflicts. You may use any generic video kind of icon.

Yeah, we can do the PR in October, but please first get the designs approved in the comments of this issue till then.

**Comment by nidhishs** [comment]
This is v1.0
Just something I came up real quick. Suggest any edits/advice you might have.
![Logo-01](https://user-images.githubusercontent.com/55269918/94263290-1c37f400-ff35-11ea-85d0-6d7911af391a.png)

**Comment by nidhishs** [comment]
I have some more ideas, and I'll try to get them down. Any recommendations you give on the above post will also be considered.

**Comment by anshulahuja98** [comment]
Looks good.
But perhaps go for a video cam instead of a regular cam

@killbotXD @DarshitJain04  can you drop in your suggestions.

**Comment by killbotXD** [comment]
A clock inside a camera lens would do I think?

**Comment by nidhishs** [comment]
> A clock inside a camera lens would do I think?

So what change would you suggest in the above logo? My implementation is basically a clock inside the camera lens as you mentioned. Do you want me to remove the bubble or something?

**Comment by killbotXD** [comment]
> > A clock inside a camera lens would do I think?
> 
> So what change would you suggest in the above logo? My implementation is basically a clock inside the camera lens as you mentioned. Do you want me to remove the bubble or something?

I mean just the camera lens and a clock inside it, removing the camera body, flash etc.

**Comment by nidhishs** [comment]
> > > A clock inside a camera lens would do I think?
> > 
> > 
> > So what change would you suggest in the above logo? My implementation is basically a clock inside the camera lens as you mentioned. Do you want me to remove the bubble or something?
> 
> I mean just the camera lens and a clock inside it, removing the camera body, flash etc.

Wouldn't that look just like a clock? I'll have to add something like the shutter to make it seem like a camera

**Comment by killbotXD** [comment]
> > > > A clock inside a camera lens would do I think?
> > > 
> > > 
> > > So what change would you suggest in the above logo? My implementation is basically a clock inside the camera lens as you mentioned. Do you want me to remove the bubble or something?
> > 
> > 
> > I mean just the camera lens and a clock inside it, removing the camera body, flash etc.
> 
> Wouldn't that look just like a clock? I'll have to add something like the shutter to make it seem like a camera

yeah that is what I was thinking a shutter and a clock inside it. If that does not look good then something that looks more like a webcam rather than a professional camera will suffice.

**Comment by nidhishs** [comment]
Sure. I'll try it out and share.

**Comment by nidhishs** [comment]
Here are some more designs.

![Logo-04](https://user-images.githubusercontent.com/55269918/94295215-31c31300-ff61-11ea-8cc9-2a7eb59484c2.png)
![Logo-03](https://user-images.githubusercontent.com/55269918/94295220-325ba980-ff61-11ea-95b9-634607b6c560.png)
![Logo-02](https://user-images.githubusercontent.com/55269918/94295224-32f44000-ff61-11ea-906c-428cc8cb9f91.png)

**Comment by killbotXD** [comment]
The shutter and the webcam look good, can we invert the foreground and the background color(with the background being circular or similar to the first design), and also decrease the shutter area and increase the area for the clock hands(and their size a little as well, they look small atm)

**Comment by anshulahuja98** [comment]
@killbotXD  @nidhishs If there is some consensus on the icon. @nidhishs you should send a PR now.

**Comment by nidhishs** [comment]
Sorry for ghosting you guys for a couple days. Was busy with some assignments. This should be the final icon according to the suggestion given by @killbotXD.
![Asset 2@0 5x](https://user-images.githubusercontent.com/55269918/94975561-5e9f9900-0512-11eb-8d59-daa4aeeed0b7.png)

Also I don't exactly know in which format and how you guys want the icon, so please let me know. I'll make the PR accordingly.

**Comment by killbotXD** [comment]
Can you invert the colours @nidhishs

**Comment by DarshitJain04** [comment]
> Sorry for ghosting you guys for a couple days. Was busy with some assignments. This should be the final icon according to the suggestion given by @killbotXD.
> ![Icon](https://user-images.githubusercontent.com/55269918/94975663-a9211580-0512-11eb-91b0-4a15a8a8ec2c.png)
> 
> Also I don't exactly know in which format and how you guys want the icon, so please let me know. I'll make the PR accordingly.

Hey @nidhishs we want the logo in .png format and the size should be 16x16px, 32x32px, 48x48px and 128x128px
Along with that one more 128x128px logo but the actual icon size should be 96x96px; an additional 16 pixels per side should be transparent padding, adding up to 128x128 total image size.

**Comment by nidhishs** [comment]
> Can you invert the colours @nidhishs

![Icon-02](https://user-images.githubusercontent.com/55269918/94988437-73f5e100-056d-11eb-9712-3a91bf06b0cd.png)

I hope this is what you mean. I'm a little confused about what you mean by inverting the colours @killbotXD.

@DarshitJain04 Got it. Confirm the design, and I'll export the logo according to the required settings.

**Comment by DarshitJain04** [comment]
> > Can you invert the colours @nidhishs
> 
> ![Icon-02](https://user-images.githubusercontent.com/55269918/94988437-73f5e100-056d-11eb-9712-3a91bf06b0cd.png)
> 
> I hope this is what you mean. I'm a little confused about what you mean by inverting the colours @killbotXD.
> 
> @DarshitJain04 Got it. Confirm the design, and I'll export the logo according to the required settings.

Looks awesome!!

**Comment by killbotXD** [comment]
> This is v1.0
> Just something I came up real quick. Suggest any edits/advice you might have.
> I used the colours I saw in the UI of your extension.
> 
> ![Logo-01](https://user-images.githubusercontent.com/55269918/94263290-1c37f400-ff35-11ea-85d0-6d7911af391a.png)
> 

I was talking about the strokes being white and the background be colored like this but the one you shared right now also looks good.

**Comment by nidhishs** [comment]
> I was talking about the strokes being white and the background be colored like this but the one you shared right now also looks good.

So are we good to export this design as the final one in the required resolution?

**Comment by killbotXD** [comment]
> > > Can you invert the colours @nidhishs
> > 
> > 
> > ![Icon-02](https://user-images.githubusercontent.com/55269918/94988437-73f5e100-056d-11eb-9712-3a91bf06b0cd.png)
> > I hope this is what you mean. I'm a little confused about what you mean by inverting the colours @killbotXD.
> > @DarshitJain04 Got it. Confirm the design, and I'll export the logo according to the required settings.
> 
> Looks awesome!!

yeah go ahead with this and the mentioned resolution 👍
