### ISSUE TITLE
Make category in upcoming

### ISSUE THREAD

**Issue by hirenchalodiya1** [devlup-labs/meet-scheduler#54]
Make collapsable categories in upcoming.
Like Today, Tomorrow, and then date wise

**Comment by utkarsh4321** [comment]
Hi i can contribute on to this

**Comment by hirenchalodiya1** [comment]
sure @utkarsh4321

**Comment by neeraj-2** [comment]
@utkarsh4321 are u still on it?

**Comment by DarshitJain04** [comment]
@utkarsh4321 any updates?

**Comment by utkarsh4321** [comment]
Hi @DarshitJain04  I didn't start yet I will start asap and ping you.

**Comment by utkarsh4321** [comment]
Hii @DarshitJain04 can you explain to me this what you really want so I will start working on it.

**Comment by DarshitJain04** [comment]
> Hii @DarshitJain04 can you explain to me this what you really want so I will start working on it.

As of now the alarms are getting displayed according to date and time. What we want is to create a collapsible list where in the list with title `Today` shows alarms that are scheduled for today, `Tomorrow` shows the alarms scheduled for next day and the rest of the alarms are left as it is or maybe another collapsible list with title `Later`

**Comment by utkarsh4321** [comment]
ok

**Comment by utkarsh4321** [comment]
Hii @DarshitJain04 can you tell me how i will see the logs of popup.jsx

**Comment by DarshitJain04** [comment]
> Hii @DarshitJain04 can you tell me how i will see the logs of popup.jsx

Right click on the popup and inspect. The console logs for popup appears will appear in a different window.

**Comment by utkarsh4321** [comment]
Hii can i use accordion for this work.

**Comment by DarshitJain04** [comment]
> Hii can i use accordion for this work.

Yeah @utkarsh4321

**Comment by utkarsh4321** [comment]
Hii submitted the PR you please check it and tell me if there is any problem.I will try to solve asap.

**Comment by utkarsh4321** [comment]
Hii in .github/workflows/pull_request file
Build pr/${{ github.event.pull_request.number }} i think this line have some / problem. Please check it.

**Comment by hirenchalodiya1** [comment]
@utkarsh4321 workflow issue solved.
can you add the issue number that you solved in the PR description? e.g Fixes #[number] or Resolves #[number]

**Comment by hirenchalodiya1** [comment]
@utkarsh4321 when you add next commit make sure to pull workflow fix from devlup-labs/master first
