### ISSUE TITLE
Time until next meeting/class

### ISSUE THREAD

**Issue by anshulahuja98** [devlup-labs/meet-scheduler#57]
A countdown to show when is the next meeting or class.
This can be shown below the buttons on the home page. 
And also on top of the "Upcoming" page

**Comment by andreepratama27** [comment]
Hi, in the upcoming pages, is it already descending to the nearest time to start?

**Comment by killbotXD** [comment]
Yeah it shows the next class/meeting at the top.

**Comment by Shantanu-Bakshi** [comment]
hey @DarshitJain04  can you specifically tell what's the issue please?

**Comment by DarshitJain04** [comment]
> hey @DarshitJain04  can you specifically tell what's the issue please?

Yeah, so basically we want to add a countdown sort of which shows the time left for the next class.
This can be added below the buttons on the home page and maybe on top of the alarms in the **Upcoming** Tab

**Comment by DarshitJain04** [comment]
> Hi, in the upcoming pages, is it already descending to the nearest time to start?
 
@andreepratama27 are you still on it? If no, then @Shantanu-Bakshi can work on it

**Comment by andreepratama27** [comment]
Not yet, sorry because still learn the repo. Its okay if you wanna pass to another 🙏

**Comment by DarshitJain04** [comment]
> Not yet, sorry because still learn the repo. Its okay if you wanna pass to another 🙏

No problem! If you want you can work on some other issue once you get familiar with the code base.
So @Shantanu-Bakshi you can work on it!

**Comment by Shantanu-Bakshi** [comment]
ok cool !

**Comment by Shantanu-Bakshi** [comment]
yeah but even I am working w/the repo so...

**Comment by killbotXD** [comment]
so I assume neither @Shantanu-Bakshi or @andreepratama27 wants to be assigned the issue?

**Comment by neeraj-2** [comment]
can i work on it?

**Comment by Shantanu-Bakshi** [comment]
@neeraj I am on it

**Comment by Shantanu-Bakshi** [comment]
@anshul should the timer show the remaining time even if it is greater than  24 hrs ? or can we show some stock message  ?

**Comment by DarshitJain04** [comment]
> @anshul should the timer show the remaining time even if it is greater than  24 hrs ? or can we show some stock message  ?
> 

@Shantanu-Bakshi you've tagged wrong Anshul...it's @anshulahuja98

**Comment by anshulahuja98** [comment]
Within 24 hrs should be okay.

**Comment by anshulahuja98** [comment]
Otherwise just hide it.
