### ISSUE TITLE
Add other google meet utility abilities

### ISSUE THREAD

**Issue by anshulahuja98** [devlup-labs/meet-scheduler#58]
Parent issue to track the development of other support features.
Example functionalities to include:
- Toggle mic to speak by pressing a key (mute/unmute)
- Leave confirmation

Other ideas can be inspired from https://chrome.google.com/webstore/detail/ljojmlmdapmnibgflmmminacbjebjpno

Add new issues addressing these points, and link them to this parent issue.

**Comment by hirenchalodiya1** [comment]
refer to this commit `56c918c897d53a6fb712ab0d1144d0093f641a62`
this will create `meet.bundle.js`
