### ISSUE TITLE
Change time format

### ISSUE THREAD

**Issue by anshulahuja98** [devlup-labs/meet-scheduler#65]
In upcoming tab show time in 12 hour format.

**Comment by neeraj-2** [comment]
I would like to work on it. Can I?

**Comment by anshulahuja98** [comment]
Sure

**Comment by andreepratama27** [comment]
Hi, can i take this?

**Comment by neeraj-2** [comment]
> Hi, can i take this?

@andreepratama27 I am already on it.You can work on some other issue.
