### ISSUE TITLE
Fetch links from classroom

### ISSUE THREAD

**Issue by Horuyuki** [devlup-labs/meet-scheduler#83]
Hello dev!

So I installed the extension, but still, following the READ.ME I was not able to find my courses in the drop down menu. Would you like posting a very detailed step by step where to click kind of description? I really just can't get something so great working.

Thanks!

**Comment by DarshitJain04** [comment]
> Hello dev!
> 
> So I installed the extension, but still, following the READ.ME I was not able to find my courses in the drop down menu. Would you like posting a very detailed step by step where to click kind of description? I really just can't get something so great working.
> 
> Thanks!

Hi @ch92787830 
Only IIT Jodhpur students have their courses in the list provided. Others can add alarms from the `Custom` tab. I hope this helps.

**Comment by ch92787830** [comment]
Oh, so it was only designed for one school's course.

Is it possible for you to design it to click on the class stream comment instead of needing the direct link? Since mine always changes.

**Comment by DarshitJain04** [comment]
> Oh, so it was only designed for one school's course.
> 
> Is it possible for you to design it to click on the class stream comment instead of needing the direct link? Since mine always changes.

Yeah, those courses are for IIT Jodhpur students. But you can use the `Custom` tab.
What exactly do you mean by "class stream comment"?

**Comment by ch92787830** [comment]
So I mean if you can make the program click on this link:

https://imgur.com/a/hYUOKvP

The one under the title. 
So that way I can paste this link:

`https://classroom.google.com/u/3/c/random-classroom-link`

Instead of the direct meeting link since that fails sometimes. And the extension click on the link under the title, then brings me to the meet page there, close the mic and camera. 

Though I have noticed that it only brings me to the meet page, can you make it so that it also presses the join button?

**Comment by DarshitJain04** [comment]
> So I mean if you can make the program click on this link:
> 
> https://imgur.com/a/hYUOKvP
> 
> The one under the title.
> So that way I can paste this link:
> 
> `https://classroom.google.com/u/3/c/random-classroom-link`
> 
> Instead of the direct meeting link since that fails sometimes. And the extension click on the link under the title, then brings me to the meet page there, close the mic and camera.
> 
> Though I have noticed that it only brings me to the meet page, can you make it so that it also presses the join button?

Oh, so you want the extension to fetch the link from google classroom itself?
We will surely see if that is possible or not.

And talking about the mic and camera button, the extension does turn off the camera and microphone and clicks on the _Join_ button (Unless you have turned off the `Auto Join Class` option in the settings)

**Comment by ch92787830** [comment]
Sorry for not responding, email notification didn't come. Yeah, to fetch the link form the stream page I linked and then use that to join. Do you think you can do it?

**Comment by ch92787830** [comment]
And yes, auto join still does not work
It brings me to the join page with the preview but not click the join button then

**Comment by DarshitJain04** [comment]
> And yes, auto join still does not work
> It brings me to the join page with the preview but not click the join button then

Is the `Auto Join Class` switch on in the settings tab? And is that sometimes you face internet issues?

**Comment by ch92787830** [comment]
It is on, and my internet is fine. It is just that the extension idles after joining the meet prepare page.

**Comment by DarshitJain04** [comment]
> It is on, and my internet is fine. It is just that the extension idles after joining the meet prepare page.

I just tried again and it is working completely fine.
Maybe just try to re-install it because it works completely fine.
