### ISSUE TITLE
Auto Join problem when session is being recorded

### ISSUE THREAD

**Issue by digick** [devlup-labs/meet-scheduler#85]
Hi,

The scheduler works per described except when the session is being recorded.
When the session is recorded, auto join cannot complete and gets stuck as per screenshot below.
Any suggestion to overcome this?

<img width="807" alt="cannot auto join" src="https://user-images.githubusercontent.com/81337964/112403876-39197c80-8d4a-11eb-991a-548c84fcce27.png">

**Comment by DarshitJain04** [comment]
> Hi,
> 
> The scheduler works per described except when the session is being recorded.
> When the session is recorded, auto join cannot complete and gets stuck as per screenshot below.
> Any suggestion to overcome this?
> 
> <img alt="cannot auto join" width="807" src="https://user-images.githubusercontent.com/81337964/112403876-39197c80-8d4a-11eb-991a-548c84fcce27.png">

Hey @digick 
Thanks for letting us know about this. We will surely surely solve this issue 😃

**Comment by 11happy** [comment]
I checked it but it is able to join recorded meetings

**Comment by 11happy** [comment]
[https://drive.google.com/file/d/1murl7PpxPMH8hFUJPV2qwCywnbOOxNGZ/view]
here's the video attached which shows it can join recorded meetings

**Comment by 11happy** [comment]
https://user-images.githubusercontent.com/76656712/119384376-3ef7f380-bce2-11eb-80d2-e6ab760898fd.mp4

**Comment by DarshitJain04** [comment]
I think this is because you are using IITJ email. If you try to join it using a different account, the issue still persists.
