### ISSUE TITLE
404 error on GET request to fetch Course and Slots data from Google Sheet

### ISSUE THREAD

**Issue by DarshitJain04** [devlup-labs/meet-scheduler#91]
Because of some updates in the Google Sheet version, the current version gives a 404 error on a GET request to fetch Course and Slots data for IIT Jodhpur students.

**Comment by DarshitJain04** [comment]
@11happy please make the necessary changes as soon as possible

**Comment by 11happy** [comment]
will try to do it as soon as possible. But it may take some time, as we have to shift it completely from googlesheets api v3 to v4 because v3 is deprecated now.

**Comment by DarshitJain04** [comment]
Hey @11happy 
Any updates?
